---
title: "Investigating higher order interactions in single cell data with scHOT."
author:
- name: Shila Gazanfar
  affiliation: University of Cambridge

output:
  BiocStyle::html_document
---

# Abstract

Single-cell RNA-sequencing has transformed our ability to examine cell fate choice. For example, in the context of development and differentiation, computational ordering of cells along ‘pseudotime’ enables the expression profiles of individual genes, including key transcription factors, to be examined at fine scale temporal resolution. However, while cell fate decisions are typically marked by profound changes in expression, many such changes are downstream of the initial cell fate decision. By contrast, more subtle changes in patterns of correlation and higher order interactions between genes across pseudotime have been associated with the fate choice itself.

We describe a novel approach, scHOT – single cell Higher Order Testing - which provides a flexible and statistically robust framework for identifying changes in higher order interactions among genes. scHOT is general and modular in nature, can be run in multiple data contexts such as along a continuous trajectory, between discrete groups, and over spatial orientations; as well as accommodate any higher order measurement such as variability or correlation. scHOT meaningfully adds to first order effect testing, such as differential expression, and provides a framework for interrogating higher order interactions from single cell data.

