---
title: "Orchestrating Single-Cell RNA-Sequencing Analysis with Bioconductor"
author:
- name: Assistant Professor Stephanie Hicks
  affiliation: Department of Biostatistics, Johns Hopkins Bloomberg School of Public Health, Baltimore, MD USA
output:
  BiocStyle::html_document
---

# Abstract

Bioconductor is the pre-eminent, open-source, open-development software project based on the R programming language for analysis and comprehension of high-throughput data in genomics, including the analysis of gene expression data. Recent advances in biotechnology have led to quantifying gene expression in individual cells and inspired the formation of large-scale data generation projects quantifying gene expression at the single-cell level, which demand fast and memory-efficient computational methods and software to successfully derive biological insights. To address this need, Bioconductor has recently developed a rich set of computational methods, standard data infrastructure, interactive data visualization tools and software packages for the analysis of single-cell gene expression data. Here, we present an overview for prospective users and contributors.  

# Brief bio

Stephanie Hicks is an Assistant Professor in the Department of Biostatistics at Johns Hopkins Bloomberg School of Public Health. She is also a faculty member of the Johns Hopkins Data Science Lab and co-founder of R-Ladies Baltimore. Her research interests focus around developing statistical methods, tools and software for the analysis of single-cell genomics data. She actively contributes software packages to the Bioconductor project and is involved in teaching courses for data science and the analysis of genomics data. For more information, please see http://www.stephaniehicks.com/.