---
title: "Getting help and helping others (including future you)"
author:
- name: Peter Hickey
  affiliation: Walter and Eliza Hall Institute of Medical Research
output:
  BiocStyle::html_document
---

# Abstract

With more than 2500 packages, even the most experienced Bioconductor user will find themselves asking, "how do I do this?", "what tool should I be using?", or generally just in need of some help or advice for a data analysis or package development. This talk will provide guidance on finding answers to your questions, answering other people's questions, and helping people (including you) on both sides of the process. The Bioconductor community, and the broader open source and open science movements, are incredible resources for getting answers to questions about data analysis, choosing and using the right tool for the job, and developing software. However, it can sometimes be difficult to know where to look for answers to your question or where to ask when you can't find the answer or need clarification. Just as important as knowing where to ask is knowing how to ask: well-formed questions contain sufficient detail for someone to help you and attract better responses. On the other side of the coin, answering a questions takes practice, too, especially while taking into account the wide variety of backgrounds amongst users of Bioconductor software. This talk will cover common types of questions, provide advice on asking well-formed questions, and help you decide the best venue for a question (e.g., public vs. safe spaces, Bioconductor support forum, GitHub issues, Biostars, mailing lists, Slack). I will describe how to produce a reproducible example ("reprex") and touch on important related issues such as online etiquette.

