---
title: "scMerge: Integration of multiple single-cell transcriptomics datasets leveraging stable expression and pseudo-replication"
author:
- name: Yingxin Lin
  affiliation: School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia 
- name: Shila Ghazanfar
  affiliation: School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia <br> Charles Perkins Centre, University of Sydney, Sydney, NSW 2006, Australia 
- name: Kevin Wang
  affiliation: School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia 
- name: Johann A. Gagnon-Bartsch
  affiliation: Department of Statistics, University of Michigan, USA 
- name: Kitty K. Lo
  affiliation: School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia 
- name: Xianbin Su
  affiliation: Key Laboratory of Systems Biomedicine (Ministry of Education) and Collaborative Innovation Center of Systems Biomedicine, Shanghai Center for Systems Biomedicine, Shanghai Jiao Tong University, Shanghai 200240, China
- name: Ze-Guang Han
  affiliation: Key Laboratory of Systems Biomedicine (Ministry of Education) and Collaborative Innovation Center of Systems Biomedicine, Shanghai Center for Systems Biomedicine, Shanghai Jiao Tong University, Shanghai 200240, China
- name: John T. Ormerod
  affiliation:  School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia 
- name: Terence P. Speed
  affiliation: Bioinformatics Division, Walter and Eliza Hall Institute of Medical Research, 1G Royal Parade, Parkville, VIC 3052, Australia <br> Department of Mathematics and Statistics, University of Melbourne, Melbourne, VIC 3010, Australia 
- name: Pengyi Yang
  affiliation: School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia <br> Charles Perkins Centre, University of Sydney, Sydney, NSW 2006, Australia 
- name: Jean Yee Hwa Yang
  affiliation: School of Mathematics and Statistics, University of Sydney, Sydney, NSW 2006, Australia <br> Charles Perkins Centre, University of Sydney, Sydney, NSW 2006, Australia 
output:
  BiocStyle::html_document
---

# Abstract

Abstract: Technological advances such as large scale single cell transcriptome profiling have exploded in recent years and enabled unprecedented insight into the behaviour of individual cells. In particular, Single cell RNA-Sequencing (scRNA-Seq) technology allows for cell-type specific characterization of gene expression values, towards understanding underlying biological processes. Concerted examination of multiple collections of scRNA-Seq data promises further biological insights that cannot be uncovered with individual datasets. However, such integrative analyses are challenging and require sophisticated methodologies.

To enable effective interrogation of multiple scRNA-Seq datasets, we have developed a novel algorithm, named scMerge, that removes unwanted variation by identifying stably expressed genes and utilizing pseudo-replicates across datasets. Biological knowledge such as cell type information can be easily incorporated into scMerge to further improve performance. We compared scMerge with four popular and recent batch correction methods using seven publicly available scRNA-Seq data collections that cover different tissues, species and protocols. We found that scMerge effectively removed batch and dataset-specific effects across a wide range of biological systems, which demonstrates that scMerge performs well in multiple scenarios and enhances biological discovery, including inferring cell developmental trajectories. 

## Software Availability

The scMerge R package is available at [https://sydneybiox.github.io/scMerge](https://sydneybiox.github.io/scMerge).