---
title: "A general framework for evaluating cross-platform concordance in genomic studies "
author:
- name: Tim Peters
  affiliation: Garvan Institute of Medical Research
output:
  BiocStyle::html_document
---

# Abstract

The reproducibility of scientific results from multiple sources is critical to the establishment of scientific doctrine. However, when characterising various genomic features (transcript/gene abundances, methylation levels, allele frequencies and the like), all measurements from any given technology are estimates and thus will retain some degree of error. Hence defining a “gold standard” process is dangerous, since all subsequent measurement comparisons will be biased towards that standard. In the absence of a “gold standard”, we instead provide tools for empirical assessment of the precision and sensitivity of a given group of genomic technologies and laboratory conditions via a consensus modelling method called the row-linear model, implemented in the new Bioconductor package "consensus", available in Release 3.8. This method is an application of the American Society for Testing and Materials Standard E691 for assessing interlaboratory precision and sources of variability across multiple testing sites. The package provides fast row-linear fitting, as well as graphic and numerical outputs from multiple fits that characterise platform/condition sensitivity and precision across the range of common loci provided.

**Reference**

Peters, T. J., French, H. J., Bradford, S. T., Pidsley, R., Stirzaker, C., Varinli, H., Nair, S., Qu, W., Song, J., Giles, K. A., Statham, A. S., Speirs, H., Speed, T. S. and S. J. Clark. (in press). Evaluation of cross-platform and interlaboratory concordance via consensus modelling of genomic measurements. Bioinformatics.